### ISSUE TITLE
Fail in quick demo

### ISSUE THREAD

**Issue by Eki87** [oppo-us-research/NeuLF#3]
Recently I tried to run the codes of quick demo for a glimpse of the model. However, the rendering failed given the absence of *.npy files for Ollie. This brought the following error:
FileNotFoundError: [Errno 2] No such file or directory: 'dataset/Ollie/uvsttrain.npy'
Is it possible to share the npy files, including uvsttrain.py, rgbtrain.npy, etc. or shall I make my effort to generate it through LLFF and colmap as mentioned?

**Comment by lizhong3232** [comment]
Thank you for highlighting the missing *.npy file for Ollie.

- I've made updates to the "Quick Demo" section of the README.
- Based on the revised documentation, you'll need to generate all the .npy files locally since they're too large to be pushed to the Git repository. You can do this by running the following command:
```
python src/llffProcess.py --data_dir dataset/Ollie --factor 4
```

Afterwards, you can execute src/demo_rgb.py to see the demonstration. Thanks for your understanding!

**Comment by Eki87** [comment]
Thanks for your reply and just now I successfully made it. I really appreciated the performance on nvs and wish you a nice day!
